map/map/urls.py
from django.contrib import admin
from django.urls import path, include
from pinpoint.views import marker_homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pinpoint/', include('pinpoint.urls', namespace='pinpoint')),
    path('', marker_homepage, name='hp')
]

map/pinpoint/urls.py
from django.urls import path
from . import views

app_name = 'pinpoint'

urlpatterns = [
    path('', views.marker_homepage, name='pinpoint_homepage'),
    path('markers/', views.marker_ajax, name='marker_ajax')
]

map/pinpoint/models.py
from django.db import models


class Marker(models.Model):
    name = models.CharField(max_length=250)
    lat = models.DecimalField(max_digits=8, decimal_places=6)
    lng = models.DecimalField(max_digits=9, decimal_places=6)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=1)

    class Meta:
        ordering = ('-name',)

    def __str__(self):
        return self.name

map/pinpoint/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET
from .models import Marker
from .decorator import ajax_only


def marker_homepage(request):
    return render(request,
                  'pinpoint/marker/list.html',
                  )


@ajax_only
@require_GET
def marker_ajax(request):
    markers = (Marker.objects.filter(status=1)
               .values('name', 'lat', 'lng'))

    return JsonResponse({'markers': list(markers)})

map/pinpoint/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
      <title>{% block title %}{% endblock %}</title>
      <link href="{% static 'css/leaflet/leaflet.css' %}" rel="stylesheet">
      <link href="{% static 'css/site.css' %}" rel="stylesheet">
        <script type="text/javascript">
            var mymap;
            var markers;
            var dataFilterName;
        </script>
    </head>
    <body>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <script src="{% static 'js/jquery/jquery-3.4.1.js' %}"></script>
        <script src="{% static 'js/leaflet/leaflet.js' %}"></script>
        <script src="{% static 'js/site/common.js' %}"></script>
        <script src="{% static 'js/site/map_home.js' %}"></script>
        <script  src="{% static 'js/js.cookie.min.js' %}"></script>

        <script type="text/javascript">
            var mymap;
            var markers;
            var csrftoken = Cookies.get('csrftoken');
            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        </script>
    </body>
</html>

map/pinpoint/templates/pinpoint/marker/list.html
{% extends "base.html" %}
{% block title %}Markers{% endblock %}

{% block content %}
    <div class="" id="rowScrollerAndMap">
        <div class="" id="mapContainer">
            <div class="" id="mapbox-col" >
                <center><div id="mapbox" class="" style="height: 768px;width: 1024px;"></div></center>
            </div>
        </div>
    </div>

<script type="text/javascript">
    window.onload = function(){
        mymap = mapInit();
        jQuery.ajax({
            'dataType':'json',
            type     :'GET',
            cache    : false,
            url  : '{% url "pinpoint:marker_ajax" %}',
        }).done(function(response) {
               showMap(mymap,response['markers']);
            })
    }
  </script>
{% endblock %}